mongo-uri: "mongodb://88.209.197.187:45782/"

marketplace-inventory:
  title: "&aMarketPlace"
  size: 54
  market-slots: [0,1,2,3,4,5,6,7,8,9]

next:
  item: "ARROW"
  name: "&aNext Page"
  slot: 53
previous:
  item: "ARROW"
  name: "&cPrevious Page"
  slot: 45